#!/bin/bash

echo "RUSTUP_VERSION=1.26.0" >> $GITHUB_ENV
echo "CMAKE_VERSION=3.27.7" >> $GITHUB_ENV
echo "OPENSSL_VERSION=openssl-3.1.3" >> $GITHUB_ENV
echo "LLVM_VERSION=17" >> $GITHUB_ENV
echo "MUSL_VERSION=1.2.4" >> $GITHUB_ENV
