#!/bin/bash

echo "CMAKE_VERSION=3.29.1" >> $GITHUB_ENV
echo "OPENSSL_VERSION=openssl-3.2.1" >> $GITHUB_ENV
echo "LLVM_VERSION=18" >> $GITHUB_ENV
echo "MUSL_VERSION=1.2.4" >> $GITHUB_ENV
echo "FREEBSD_MAJOR=13" >> $GITHUB_ENV
echo "OPENBSD_MAJOR=7" >> $GITHUB_ENV
